version: '3.0'

services:
  railsapp: &app
    build: ./
    image: spocket-product-search/app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - database
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:cached
      - ./bundle_cache:/bundle_cache
    env_file:
      - .environments/development/web
      - .environments/development/database
    tty: true
    stdin_open: true
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server
      - BUNDLE_PATH=/bundle_cache

  webpack_dev_server:
    build: ./
    image: spocket-product-search/app:latest
    command: bundle exec ./bin/webpack-dev-server
    depends_on:
      - railsapp
    ports:
      - "3035:3035"
    volumes:
      - .:/usr/src/app:cached
    env_file:
      - .environments/development/web
      - .environments/development/database
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - BUNDLE_PATH=/usr/src/app/bundle_cache

  spring:
    build: ./
    image: spocket-product-search/app:latest
    command: bundle exec spring server
    depends_on:
      - railsapp
    volumes:
      - .:/usr/src/app:cached
      - ./bundle_cache:/bundle_cache
    env_file:
      - .environments/development/web
      - .environments/development/database
    tty: true
    environment:
      - BUNDLE_PATH=/bundle_cache
    pid: host
    networks:
      default:
        aliases:
          - web.com
          - subdomain.web.com
          - subdomain2.web.com

  database:
    image: postgres
    env_file:
      - .environments/development/database
    volumes:
      - db_data:/var/lib/postgresql/data:cached

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  db_data:
  bundle_cache:
  elasticsearch-data:
